server:
  port: 8088
  servlet:
    context-path: /wx-login

spring:
  application:
    name: wx-login
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wx.wxlogin.pojo
